_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cache_control_override: 0
  ckeditor5: 0
  comment: 0
  config: 0
  contact: 0
  content_access: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dblog: 0
  devel: 0
  devel_entity_updates: 0
  draggableviews: 0
  draggableviews_demo: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_clone: 0
  entity_reference_revisions: 0
  entity_reference_views: 0
  facets: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  flag: 0
  flag_bookmark: 0
  flag_count: 0
  flag_follower: 0
  gin_toolbar: 0
  google_maps_services: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_droppable: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  menu_item_extras: 0
  menu_item_role_access: 0
  menu_link_content: 0
  menu_trail_by_path: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  search_api: 0
  search_api_db: 0
  search_api_page: 0
  select2: 0
  serialization: 0
  shortcut: 0
  simple_gmap: 0
  simple_menu_icons: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  social_link_field: 0
  social_media_links: 0
  social_media_links_field: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_bulk_operations: 0
  views_ui: 0
  webform: 0
  webform_access: 0
  webform_node: 0
  webform_ui: 0
  extlink: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  olivero: 0
  claro: 0
  gin: 0
  exem: 0
profile: standard
