cloneable_entities:
  - block
  - block_content_type
  - block_content
  - comment
  - comment_type
  - contact_form
  - contact_message
  - editor
  - field_storage_config
  - field_config
  - file
  - filter_format
  - flagging
  - flag
  - image_style
  - media_type
  - media
  - menu_link_content
  - node
  - node_type
  - path_alias
  - search_page
  - shortcut
  - shortcut_set
  - slick
  - action
  - menu
  - taxonomy_term
  - taxonomy_vocabulary
  - tour
  - user_role
  - user
  - webform_options
  - webform_submission
  - webform
  - webform_access_type
  - webform_access_group
  - pathauto_pattern
  - view
  - paragraph
  - paragraphs_type
  - base_field_override
  - date_format
  - entity_view_display
  - entity_form_mode
  - entity_form_display
  - entity_view_mode
  - like
  - search_api_task
  - search_api_server
  - search_api_index
  - facets_facet
  - facets_facet_source
  - search_api_page
  - fixed_block_content
  - menu_position_rule
